### ISSUE TITLE
tableClass.remark和field.remark在模板中无法解析并报错

### ISSUE THREAD

**Issue by werthpt** [baomidou/MybatisX#30]
我使用的是MySQL，并且每个字段都有注释

![image](https://user-images.githubusercontent.com/13556014/120468203-8b72bb80-c3d3-11eb-84f6-297adaa561fb.png)

`填充模板出错,FreeMarker template error:  
The following has evaluated to null or missing:  
==> field.remark  [in template "template" at line 27, column 10]  
Tip: It's the step after the last dot that caused this error, not those before it.  
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??  
FTL stack trace ("~" means nesting-related):  
	- Failed at: ${field.remark}  [in template "template" at line 27, column 7]  
Java stack trace (for programmers):  
freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]  
	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134)  
	at freemarker.core.EvalUtil.coerceModelToTextualCommon(EvalUtil.java:479)
	at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:401)
	at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:370)
	at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100)
	at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
	at freemarker.core.Environment.visit(Environment.java:367)
	at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:643)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)`

**Comment by ls9527** [comment]
这属于freemarker的解析有问题， ${field.remark} 改为 ${field.remark!} 就可以了
