### ISSUE TITLE
java.lang.NoClassDefFoundError: com/intellij/aop/psi/AopPointcutExpressionFile

### ISSUE THREAD

**Issue by longjians** [baomidou/MybatisX#42]
java.lang.NoClassDefFoundError: com/intellij/aop/psi/AopPointcutExpressionFile
	at com.intellij.spring.model.xml.aop.PointcutExpressionConverter.fromString(PointcutExpressionConverter.java:32)
	at com.intellij.spring.model.xml.aop.PointcutExpressionConverter.fromString(PointcutExpressionConverter.java:22)
	at com.intellij.util.xml.impl.GetInvocation.getValueInner(GetInvocation.java:99)
	at com.intellij.util.xml.impl.GetInvocation.getOrCalcValue(GetInvocation.java:74)
	at com.intellij.util.xml.impl.GetInvocation.invoke(GetInvocation.java:62)
	at com.intellij.util.xml.impl.DomInvocationHandler.invoke(DomInvocationHandler.java:660)
	at com.intellij.util.xml.GenericAttributeValue$$EnhancerByJetBrainsMainCglib$$f4a47684.getValue(<generated>)
	at com.intellij.util.xml.highlighting.DomHighlightingHelperImpl.checkResolveProblems(DomHighlightingHelperImpl.java:127)
	at com.intellij.util.xml.highlighting.BasicDomElementsInspection.checkDomElement(BasicDomElementsInspection.java:63)
	at com.baomidou.plugin.idea.mybatisx.inspection.MapperXmlInspection.checkDomElement(MapperXmlInspection.java:27)
	at com.intellij.util.xml.highlighting.DomElementsInspection$1.consume(DomElementsInspection.java:67)
	at com.intellij.util.xml.highlighting.DomElementsInspection$1.consume(DomElementsInspection.java:63)
	at com.intellij.util.xml.highlighting.DomElementsInspection.checkChildren(DomElementsInspection.java:82)
	at com.intellij.util.xml.highlighting.DomElementsInspection$1.consume(DomElementsInspection.java:66)
	at com.intellij.util.xml.highlighting.DomElementsInspection$1.consume(DomElementsInspection.java:63)
	at com.intellij.util.xml.highlighting.DomElementsInspection.checkChildren(DomElementsInspection.java:82)
	at com.intellij.util.xml.highlighting.DomElementsInspection$1.consume(DomElementsInspection.java:66)
	at com.intellij.util.xml.highlighting.DomElementsInspection$1.consume(DomElementsInspection.java:63)
	at com.intellij.util.xml.highlighting.DomElementsInspection.checkChildren(DomElementsInspection.java:82)
	at com.intellij.util.xml.highlighting.DomElementsInspection$1.consume(DomElementsInspection.java:66)
	at com.intellij.util.xml.highlighting.DomElementsInspection$1.consume(DomElementsInspection.java:63)
	at com.intellij.util.xml.highlighting.DomElementsInspection.checkFileElement(DomElementsInspection.java:70)
	at com.intellij.util.xml.highlighting.DomElementAnnotationsManagerImpl.checkFileElement(DomElementAnnotationsManagerImpl.java:203)
	at com.intellij.util.xml.highlighting.DomElementsInspection.checkDomFile(DomElementsInspection.java:143)
	at com.intellij.util.xml.highlighting.DomElementsInspection.checkFile(DomElementsInspection.java:117)
	at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:145)
	at com.intellij.psi.impl.source.xml.XmlFileImpl.accept(XmlFileImpl.java:57)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:64)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$7(LocalInspectionsPass.java:352)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:172)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:109)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$10(LocalInspectionsPass.java:352)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by longjians** [comment]
IntelliJ IDEA 2021.2 (Ultimate Edition)
Build #IU-212.4746.92, built on July 27, 2021
