### ISSUE TITLE
Version 1.5.0, "Result type not match" points to the same type, and the plugin pops up an error message

### ISSUE THREAD

**Issue by linghengqian** [baomidou/MybatisX#46]
**operating system**:
Windows 10 19043.1237
**Plugin version**:
1.5.0
**idea version**:
2021.2.2
**Problem Description**:
When MybatisX is enabled for the project, an error is reported when trying to solve the problem with the alt+enter key, and clearing the cache is still invalid.
This issue comes from the transfer of gitee.
**Steps to reproduce**
Operate alt+enter on the explosion of a mapper layer, and an IDE error message appears.
![image](https://user-images.githubusercontent.com/20187731/139528552-e39acd27-5997-4c55-819d-dd1d72400a0a.png)
![image](https://user-images.githubusercontent.com/20187731/139528555-5adf4eaa-0b6e-42fe-a8e9-fc5f94bfb454.png)

**Error message**
```shell
com.intellij.diagnostic.PluginException: Inspection #MybatisXMapperMethodInspection has no description [Plugin: com.baomidou.plugin.idea.mybatisx]
	at com.intellij.codeInspection.ui.InspectionNodeInfo.<init>(InspectionNodeInfo.java:72)
	at com.intellij.codeInspection.ui.InspectionResultsView.createBaseRightComponentFor(InspectionResultsView.java:475)
	at com.intellij.codeInspection.ui.InspectionResultsView.showInRightPanel(InspectionResultsView.java:402)
	at com.intellij.codeInspection.ui.InspectionResultsView.syncRightPanel(InspectionResultsView.java:341)
	at com.intellij.codeInspection.ui.InspectionTree.lambda$new$0(InspectionTree.java:78)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:641)
	at com.intellij.ui.treeStructure.Tree$MySelectionModel.fireValueChanged(Tree.java:627)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1111)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:297)
	at java.desktop/javax.swing.JTree.setSelectionPaths(JTree.java:1669)
	at java.desktop/javax.swing.JTree.setSelectionRows(JTree.java:1752)
	at java.desktop/javax.swing.JTree.setSelectionRow(JTree.java:1727)
	at com.intellij.util.ui.tree.TreeUtil.lambda$showAndSelect$10(TreeUtil.java:641)
	at com.intellij.util.ui.tree.TreeUtil.showAndSelect(TreeUtil.java:676)
	at com.intellij.util.ui.tree.TreeUtil.showAndSelect(TreeUtil.java:596)
	at com.intellij.util.ui.tree.TreeUtil.showAndSelect(TreeUtil.java:591)
	at com.intellij.util.ui.tree.TreeUtil.selectPath(TreeUtil.java:506)
	at com.intellij.util.ui.tree.TreeUtil.selectPath(TreeUtil.java:488)
	at com.intellij.codeInspection.ui.InspectionTree.selectNode(InspectionTree.java:232)
	at com.intellij.codeInspection.ui.InspectionViewNavigationPanel$1.doClick(InspectionViewNavigationPanel.java:67)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:389)
	at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:363)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6652)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:814)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by linghengqian** [comment]
This problem appears to have been improved considerably in `1.5.1`. I will close this issue.
